config/routes.rb
Rails.application.routes.draw do

  # As a user, I can list tasks
  get "tasks", to: "tasks#index"

  # As a user, I can add a new task
  # step1 get the form
  get "tasks/new", to: "tasks#new"

  # As a user, I can view the details of a task
  get "tasks/:id", to: "tasks#show", as: :task

  # step2 post create form
  post "tasks", to: "tasks#create", as: :new_task

  # As a user, I can edit a task (mark as completed / update title & details)
  # Step 1, GET the form
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  # Step 2, PATCH the form
  patch "tasks/:id", to: "tasks#update"

  # As a user, I can remove a task
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
    #to index
  end

  def edit
  end

  def update
    @task.update(edit_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end


  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def edit_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/tasks/index.html.erb
<h1>YOUR TASKS</h1>
<div class="index-container">
  <% @tasks.each do |task| %>
    <!-- link_to "ANCHOR", path -->
    <% if task.completed %>
      <i class="far fa-check-square"></i>
    <% else %>
      <i class="far fa-square"></i>
    <% end %>
    <span><%= link_to task.title, task_path(task.id) %></span>
    <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
</div>
<%= link_to tasks_new_path do %>
  <p><i class="fa fa-plus"></i> Add a new task</p>
<% end %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= simple_form_for(@task) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :details %>
      <%= f.text_field :details %>
      <%= f.submit :submit%>
    <% end %>
  </div>
  <hr>
  <%= link_to tasks_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to edit_task_path(@task.id), class: 'pull-right btn btn-default' do %>
  <i class="fa fa-pencil"></i> Edit this task
<% end %>
<h1>Task detail</h1>
<h2><%= @task.title %></h2>
<p class="well"><%= @task.details %></p>
<% if @task.completed %>
  <i class="far fa-check-square"></i>
<% else %>
  <i class="far fa-square"></i>
<% end %>
<h3><%= link_to "Back to Main",tasks_path %></h3>